### ISSUE TITLE
AoT compilation fails with ngSemantic

### ISSUE THREAD

**Issue by rkrayovskyy** [vladotesanovic/ngSemantic#86]
Hello,

first of all, thank you for a great and helpful job done!

I am trying to compile app for AoT according to the following official guide https://angular.io/docs/ts/latest/cookbook/aot-compiler.html with ngSemantic installed and configured according to your guide.

All works fine in dev mode.

The following issue raises when I do AoT compilation:

```
Error: Unexpected value 'NgSemanticModule' imported by the module 'AppModule'
    at /Users/*****/*****/******/node_modules/@angular/compiler/bundles/compiler.umd.js:14126:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/*****/*****/******/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
    at /Users/*****/*****/******/node_modules/@angular/compiler/bundles/compiler.umd.js:12952:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/*****/*****/******/node_modules/@angular/compiler/bundles/compiler.umd.js:12951:21)
    at CodeGenerator.codegen (/Users/*****/*****/******/node_modules/@angular/compiler-cli/src/codegen.js:105:47)
    at codegen (/Users/*****/*****/******/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Users/*****/*****/******/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/Users/*****/*****/******/node_modules/@angular/compiler-cli/src/main.js:14:9)
Compilation failed
```

**Comment by vladotesanovic** [comment]
Ok, to be honest i didn't try AOT, i read about it and i get impression that it is not ready yet. Did you try AOT with other external libraries in your project? That works?

**Comment by rkrayovskyy** [comment]
yes, I did.

I don't have many of them at this stage:
'ng2-toastr':                 'npm:ng2-toastr',
'ng-semantic':                'npm:ng-semantic',
'ng2-facebook-sdk':           'npm:ng2-facebook-sdk'

Others work fine so far.

**Comment by rkrayovskyy** [comment]
Hi Vlad,

just to be clear and know what to do next - are you planning to look into this issue in the nearest time, or it is not a priority yet?


thanks,
Roman

**Comment by arsenys** [comment]
Having same problem with Webpack 2 and AoT

**Comment by rkrayovskyy** [comment]
@arsenys by any chance, any success with compiling it?

**Comment by prayagmk** [comment]
@vladotesanovic Any update on this?

**Comment by anil1712** [comment]
I am also getting the same. Please give us any updates

**Comment by arsenys** [comment]
@vladotesanovic Still happens, just checked... :(

**Comment by anil1712** [comment]
Yeah, So you are going to look into it?

**Comment by mwamufiya** [comment]
+1

**Comment by nimaen** [comment]
Don't write +1 please, there is a github feature for that 😉

**Comment by fpmk** [comment]
Same problem for me. trying to do aot compilation with ngSemantic, getting error as TS

**Comment by enavarro222** [comment]
I guess this is the same issue than #156 and #105

**Comment by patriceo** [comment]
Has someone found a workaround for this ?

I'm considering removing ng-semantic because it no longer works with latest angular-cli rc :(

**Comment by mkndn** [comment]
Is this issue going to be fixed. I have put in lot of efforts in my app with this plugin. It would be great if this issue is fixed.

**Comment by gobeli** [comment]
There is a nasty workaround. You can get it to work, by referencing the repo in your project instead of the. package.json: 
    `"ng-semantic": "git+https://github.com/vladotesanovic/ngSemantic.git"`
And then in the module.ts
    `import { NgSemanticModule } from 'ng-semantic/ng-semantic';`
But like a said it's quite nasty and I don't recommend using it for production!

**Comment by adamk33n3r** [comment]
That didn't work for me, @gobeli 

Getting errors like ` Property 'isInsideForm' is private and only accessible within class 'SemanticInputComponent'.`

**Comment by pieperu** [comment]
Is there any news on this? Is there going to be a fix. I'm debating moving away from SemanticUi all together because of this., which is a shame because i really like it as ui framework

**Comment by trevordaniels** [comment]
You could look at a similar alternative library which works with aot and doesn't use jquery. https://edcarroll.github.io/ng2-semantic-ui/

**Comment by pieperu** [comment]
This is an excellent alternative, thank you
